name: Pull Request

on:
  - pull_request

jobs:
  build-and-test:
    name: Build and test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test build output
        run: npm run test:ci

      - name: Codecov
        # Only run on one node version
        if: matrix.node-version == '22.x'
        uses: codecov/codecov-action@v5 # https://github.com/codecov/codecov-action
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Typecheck build output
        run: npm run typecheck

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:check
